name: Test package

on: [push, pull_request]

jobs:
  nox-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python-version: "3.11"
            nox-session: tests_py311_np1
          - python-version: "3.11"
            nox-session: tests_py311_np2
          - python-version: "3.13"
            nox-session: tests_py313_np2
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install nox
        run: python -m pip install --upgrade pip nox
      - name: Run matrix test session
        run: nox -s ${{ matrix.nox-session }}
